#------------------------------#
#       Config File v0.2       #
#------------------------------#

format:
  # The prefix of console logs
  prefix: '[CCMD]'
  # The prefix when referencing the full command
  # example: minecraft's /tell can be referenced via /minecraft:tell. Then minecraft is the namespace
  # format: namespace : command
  namespace: 'customcommand'
  # The placeholder format: < ph >
  placeholder-format: '<%ph>'
  # the action-holder format: < ! ah >
  actionholder-format: '<!%ah>'

dev:
  # Immediately updates commands when there are changes
  hotswap: false

# the default values for the corresponding fields in a ccmd
defaults:
  permission: 'ccmd.command.%cmd'
  usage: '/<command>' # <command> -> command's name, \n -> new line
  description: 'Server Command'

tab:
  # This will remove all ccmd's with a prefix from tab. they can still be executed just fine
  # see: command-prefix in format
  remove-namespaced-plugin-commands: false

  # This will remove all commands with a prefix from tab. they can still be executed just fine
  # If the command is "not found", your args are probably just invalid
  remove-namespaced-commands: false

# the values accepted as true, everything else is false
# CASE SENSITIVE
boolean-true:
  - 'true'
  - 'yes' # papi default

# Removes the &<c> colors. doesn't apply to ยง<c>
# Some consoles don't support colors and will take outputs literally
remove-colors-in-console: false

# only change this if some name triggers you, or you want shorter / more detailed names
# changing this will result in examples.yml not working correctly anymore
paths:
  message: '%cmd.message'
  broadcast: '%cmd.broadcast'
  aliases: '%cmd.aliases'
  description: '%cmd.description'
  usage: '%cmd.usage'
  permission: '%cmd.permission'
  permission-required: '%cmd.permission-required'
  args: '%cmd.args'
  tab: '%cmd.tab'

  # conditions right now still require this to start with '%cmd.commands', so no short versions of it :/
  # or just never use conditions...
  commands: '%cmd.commands' # placeholder: %cmds The commands path (only supported by fields in this section)
  command-condition: '%cmds.condition'
  command-condition-true: '%cmds.condition.true'
  command-condition-false: '%cmds.condition.false'

  advanced-broadcast: '%cmd.broadcast' # placeholder: %abc The advanced broadcast path (only the fields in this section support it)
  advanced-broadcast-range: '%abc.range'
  advanced-broadcast-permission: '%abc.permission'
  advanced-broadcast-condition: '%abc.condition'
  advanced-broadcast-broadcast: '%abc.broadcast'
